### ISSUE TITLE
Throws error when using React 0.14.3

### ISSUE THREAD

**Issue by CarlRosell** [orgsync/react-list#70]
When updating React I noticed that ReactList throws this error.

```
Warning: ReactList is accessing getDOMNode or findDOMNode inside its render().
render() should be a pure function of props and state.
It should never access something that requires stale data from the previous render, such as refs. 
Move this logic to componentDidMount and componentDidUpdate instead.
```

**Comment by caseywebdev** [comment]
Fixed in `0.7.5`, thanks for the report.

**Comment by CarlRosell** [comment]
Thanks!

**Comment by CarlRosell** [comment]
![React List Error](https://cloud.githubusercontent.com/assets/2036823/11336975/b69e5098-91e9-11e5-9c1d-7b103b92e44f.png)

Still see this problem. Reprocude by scrolling list with variable height. 
I can of course provide an `itemSizeGetter` function and the error goes away. 
But it would be neat if this library could handle all of that for me :smile:

**Comment by caseywebdev** [comment]
Bah this warning is annoying because it's not applicable for this case.

**Comment by caseywebdev** [comment]
Alright try `0.7.6`, the warning should be gone.

**Comment by CarlRosell** [comment]
Works great. Thanks!!
